name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # every day at 2am
  workflow_dispatch: # or manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
